### ISSUE TITLE
[BUG] __add__ function of system.py is not working

### ISSUE THREAD

**Issue by tuoping** [deepmodeling/dpdata#197]
**Summary**

When I changed 
```python
self.system_1.append(self.system_2)
```
to
```python
self.system_3=self.system_1+self.system_2
```
in tests/test_system_append.py, a pile of errors were reported.
```bash
..............[[[4.3485389  4.20903041 5.2       ]
  [2.30878039 6.27327007 1.13      ]
  [4.64061163 3.49272294 4.58      ]
  [3.97070725 3.80408719 6.03      ]
  [1.38402421 6.25106647 1.5       ]
  [2.30624337 5.88874931 0.21      ]]]
.EEEEEEEEEEEEEE
======================================================================
ERROR: test_add_func (__main__.TestVaspXmlAppend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_system_append.py", line 35, in setUp
    self.system_1 = self.system_1.sub_system([0, 12, 4, 16, 8])
  File "/home/tuoping/dpdata/dpdata/system.py", line 966, in sub_system
    tmp_sys.data = System.sub_system(self, f_idx).data
  File "/home/tuoping/dpdata/dpdata/system.py", line 286, in sub_system
    tmp.data['cells'] = self.data['cells'][f_idx].reshape(-1, 3, 3)
IndexError: index 12 is out of bounds for axis 0 with size 10

======================================================================
ERROR: test_atom_names (__main__.TestVaspXmlAppend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_system_append.py", line 35, in setUp
    self.system_1 = self.system_1.sub_system([0, 12, 4, 16, 8])
  File "/home/tuoping/dpdata/dpdata/system.py", line 966, in sub_system
    tmp_sys.data = System.sub_system(self, f_idx).data
  File "/home/tuoping/dpdata/dpdata/system.py", line 286, in sub_system
    tmp.data['cells'] = self.data['cells'][f_idx].reshape(-1, 3, 3)
IndexError: index 12 is out of bounds for axis 0 with size 10

======================================================================
ERROR: test_atom_numbs (__main__.TestVaspXmlAppend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_system_append.py", line 35, in setUp
    self.system_1 = self.system_1.sub_system([0, 12, 4, 16, 8])
  File "/home/tuoping/dpdata/dpdata/system.py", line 966, in sub_system
    tmp_sys.data = System.sub_system(self, f_idx).data
  File "/home/tuoping/dpdata/dpdata/system.py", line 286, in sub_system
    tmp.data['cells'] = self.data['cells'][f_idx].reshape(-1, 3, 3)
IndexError: index 12 is out of bounds for axis 0 with size 10

======================================================================
ERROR: test_atom_types (__main__.TestVaspXmlAppend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_system_append.py", line 35, in setUp
    self.system_1 = self.system_1.sub_system([0, 12, 4, 16, 8])
  File "/home/tuoping/dpdata/dpdata/system.py", line 966, in sub_system
    tmp_sys.data = System.sub_system(self, f_idx).data
  File "/home/tuoping/dpdata/dpdata/system.py", line 286, in sub_system
    tmp.data['cells'] = self.data['cells'][f_idx].reshape(-1, 3, 3)
IndexError: index 12 is out of bounds for axis 0 with size 10

======================================================================
ERROR: test_cell (__main__.TestVaspXmlAppend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_system_append.py", line 35, in setUp
    self.system_1 = self.system_1.sub_system([0, 12, 4, 16, 8])
  File "/home/tuoping/dpdata/dpdata/system.py", line 966, in sub_system
    tmp_sys.data = System.sub_system(self, f_idx).data
  File "/home/tuoping/dpdata/dpdata/system.py", line 286, in sub_system
    tmp.data['cells'] = self.data['cells'][f_idx].reshape(-1, 3, 3)
IndexError: index 12 is out of bounds for axis 0 with size 10

======================================================================
ERROR: test_coord (__main__.TestVaspXmlAppend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_system_append.py", line 35, in setUp
    self.system_1 = self.system_1.sub_system([0, 12, 4, 16, 8])
  File "/home/tuoping/dpdata/dpdata/system.py", line 966, in sub_system
    tmp_sys.data = System.sub_system(self, f_idx).data
  File "/home/tuoping/dpdata/dpdata/system.py", line 286, in sub_system
    tmp.data['cells'] = self.data['cells'][f_idx].reshape(-1, 3, 3)
IndexError: index 12 is out of bounds for axis 0 with size 10

======================================================================
ERROR: test_energy (__main__.TestVaspXmlAppend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_system_append.py", line 35, in setUp
    self.system_1 = self.system_1.sub_system([0, 12, 4, 16, 8])
  File "/home/tuoping/dpdata/dpdata/system.py", line 966, in sub_system
    tmp_sys.data = System.sub_system(self, f_idx).data
  File "/home/tuoping/dpdata/dpdata/system.py", line 286, in sub_system
    tmp.data['cells'] = self.data['cells'][f_idx].reshape(-1, 3, 3)
IndexError: index 12 is out of bounds for axis 0 with size 10

======================================================================
ERROR: test_force (__main__.TestVaspXmlAppend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_system_append.py", line 35, in setUp
    self.system_1 = self.system_1.sub_system([0, 12, 4, 16, 8])
  File "/home/tuoping/dpdata/dpdata/system.py", line 966, in sub_system
    tmp_sys.data = System.sub_system(self, f_idx).data
  File "/home/tuoping/dpdata/dpdata/system.py", line 286, in sub_system
    tmp.data['cells'] = self.data['cells'][f_idx].reshape(-1, 3, 3)
IndexError: index 12 is out of bounds for axis 0 with size 10

======================================================================
ERROR: test_is_pbc (__main__.TestVaspXmlAppend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_system_append.py", line 35, in setUp
    self.system_1 = self.system_1.sub_system([0, 12, 4, 16, 8])
  File "/home/tuoping/dpdata/dpdata/system.py", line 966, in sub_system
    tmp_sys.data = System.sub_system(self, f_idx).data
  File "/home/tuoping/dpdata/dpdata/system.py", line 286, in sub_system
    tmp.data['cells'] = self.data['cells'][f_idx].reshape(-1, 3, 3)
IndexError: index 12 is out of bounds for axis 0 with size 10

======================================================================
ERROR: test_len_func (__main__.TestVaspXmlAppend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_system_append.py", line 35, in setUp
    self.system_1 = self.system_1.sub_system([0, 12, 4, 16, 8])
  File "/home/tuoping/dpdata/dpdata/system.py", line 966, in sub_system
    tmp_sys.data = System.sub_system(self, f_idx).data
  File "/home/tuoping/dpdata/dpdata/system.py", line 286, in sub_system
    tmp.data['cells'] = self.data['cells'][f_idx].reshape(-1, 3, 3)
IndexError: index 12 is out of bounds for axis 0 with size 10

======================================================================
ERROR: test_nframs (__main__.TestVaspXmlAppend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_system_append.py", line 35, in setUp
    self.system_1 = self.system_1.sub_system([0, 12, 4, 16, 8])
  File "/home/tuoping/dpdata/dpdata/system.py", line 966, in sub_system
    tmp_sys.data = System.sub_system(self, f_idx).data
  File "/home/tuoping/dpdata/dpdata/system.py", line 286, in sub_system
    tmp.data['cells'] = self.data['cells'][f_idx].reshape(-1, 3, 3)
  1 import os
IndexError: index 12 is out of bounds for axis 0 with size 10

======================================================================
ERROR: test_nopbc (__main__.TestVaspXmlAppend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_system_append.py", line 35, in setUp
    self.system_1 = self.system_1.sub_system([0, 12, 4, 16, 8])
  File "/home/tuoping/dpdata/dpdata/system.py", line 966, in sub_system
    tmp_sys.data = System.sub_system(self, f_idx).data
  File "/home/tuoping/dpdata/dpdata/system.py", line 286, in sub_system
    tmp.data['cells'] = self.data['cells'][f_idx].reshape(-1, 3, 3)
IndexError: index 12 is out of bounds for axis 0 with size 10
  1 import os

======================================================================
ERROR: test_orig (__main__.TestVaspXmlAppend)
  1 import os
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_system_append.py", line 35, in setUp
    self.system_1 = self.system_1.sub_system([0, 12, 4, 16, 8])
  File "/home/tuoping/dpdata/dpdata/system.py", line 966, in sub_system
    tmp_sys.data = System.sub_system(self, f_idx).data
  File "/home/tuoping/dpdata/dpdata/system.py", line 286, in sub_system
    tmp.data['cells'] = self.data['cells'][f_idx].reshape(-1, 3, 3)
IndexError: index 12 is out of bounds for axis 0 with size 10

======================================================================
ERROR: test_virial (__main__.TestVaspXmlAppend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_system_append.py", line 35, in setUp
    self.system_1 = self.system_1.sub_system([0, 12, 4, 16, 8])
  File "/home/tuoping/dpdata/dpdata/system.py", line 966, in sub_system
    tmp_sys.data = System.sub_system(self, f_idx).data
  File "/home/tuoping/dpdata/dpdata/system.py", line 286, in sub_system
    tmp.data['cells'] = self.data['cells'][f_idx].reshape(-1, 3, 3)
IndexError: index 12 is out of bounds for axis 0 with size 10

----------------------------------------------------------------------
Ran 29 tests in 0.310s

FAILED (errors=14)
```

**Steps to Reproduce**

**Further Information, Files, and Links**

**Comment by njzjz** [comment]
They are not the same thing. `self.system_1.append(self.system_2)` means `self.system_1+=self.system_2`.

**Comment by tuoping** [comment]
OK, mark that, thank you.
