### ISSUE TITLE
[BUG] fmt="cp2k/output" unable to read CP2K log file

### ISSUE THREAD

**Issue by PWFYeung** [deepmodeling/dpdata#320]
**Summary**
Using dpdata with `fmt="cp2k/output"` returns the error:
```
Traceback (most recent call last):
  File "/scratch3/usr/felix/deepmd-wat-dcm/train-128w-36dcm-wif-interfacial-virial-240NN-manual-sel/test-lammps/36dcm/0/dcm-recal/50/generate-data.py", line 4, in <module>
    d_cp2klog.to("deepmd/raw", "dpmd_raw")
  File "/home/felix/.conda/envs/dpdata/lib/python3.10/site-packages/dpdata/system.py", line 281, in to
    return self.to_fmt_obj(load_format(fmt), *args, **kwargs)
  File "/home/felix/.conda/envs/dpdata/lib/python3.10/site-packages/dpdata/system.py", line 1026, in to_fmt_obj
    return fmtobj.to_labeled_system(self.data, *args, **kwargs)
  File "/home/felix/.conda/envs/dpdata/lib/python3.10/site-packages/dpdata/format.py", line 77, in to_labeled_system
    return self.to_system(data, *args, **kwargs)
  File "/home/felix/.conda/envs/dpdata/lib/python3.10/site-packages/dpdata/plugins/deepmd.py", line 22, in to_system
    dpdata.deepmd.raw.dump(file_name, data)
  File "/home/felix/.conda/envs/dpdata/lib/python3.10/site-packages/dpdata/deepmd/raw.py", line 64, in dump
    nframes = data['cells'].shape[0]
AttributeError: 'list' object has no attribute 'shape
```
However, using `fmt="cp2k/aimd_output"` works well without any issue.

CP2K version: 7.1
dpdata version: 0.2.7

**Steps to Reproduce**
In the attached zip file:
1. `python generate-data.py` uses dpdata with `fmt="cp2k/output"`
2. `python aimd-generate-data.py` uses dpdata with `fmt="cp2k/aimd_output"`

**Further Information, Files, and Links**
[50.zip](https://github.com/deepmodeling/dpdata/files/9000642/50.zip)

**Comment by HuangJiameng** [comment]
[https://github.com/deepmodeling/dpdata/blob/master/dpdata/cp2k/output.py](url)
Since it is based on the template of cp2k log file, the function for "cp2k/output" can't read the log file of AIMD.
