### ISSUE TITLE
[BUG] The order of elements affects the judgment of molecular formula

### ISSUE THREAD

**Issue by HuangJiameng** [deepmodeling/dpdata#333]
**Summary**

dpdata will change the order of elements in molecular formula, so KeyError is raised. The essentially same molecular formula should be recognized.

**Steps to Reproduce**
script.py
```
import dpdata
import os
sys_entire = dpdata.MultiSystems().from_deepmd_npy(os.path.join("data.rest"), labeled = False)
print(i for i in sys_entire)
print(sys_entire.systems)
subsys = sys_entire['I12Pb4C4N4H24'][0]
```
```
(base) ➜ test_dpdata python3 script.py
<generator object <genexpr> at 0x7fb43b5ecb30>
{'C4H24I12N4Pb4': Data Summary
Unlabeled System
-------------------
Frame Numbers     : 21316
Atom Numbers      : 48
Element List      :
-------------------
C  H  I  N  Pb
4  24  12  4  4, 'C8H48I24N8Pb8': Data Summary
Unlabeled System
-------------------
Frame Numbers     : 1887
Atom Numbers      : 96
Element List      :
-------------------
C  H  I  N  Pb
8  48  24  8  8}
Traceback (most recent call last):
  File "/root/test_simplify/test_dpdata/script.py", line 6, in <module>
    subsys = sys_entire['I12Pb4C4N4H24'][0]
  File "/opt/anaconda3/lib/python3.9/site-packages/dpdata-0.2.8.dev12+g3968d3d.d20220706-py3.9.egg/dpdata/system.py", line 1158, in __getitem__
    return self.systems[key]
KeyError: 'I12Pb4C4N4H24'
```
data is too large to attach

**Comment by HuangJiameng** [comment]
`type_map` can solve this problem
