### ISSUE TITLE
[BUG]When I use a script to convert OUTCAR to npy format, I encounter the following error：

### ISSUE THREAD

**Issue by BraunSakai** [deepmodeling/dpdata#348]
[dp.zip](https://github.com/deepmodeling/dpdata/files/9421062/dp.zip)

Traceback (most recent call last):
  File "/work/wq/zcx/dtwistNiN2/0/dp/cov-outcar2dp.py", line 4, in <module>
    dsys.to('deepmd/npy', 'deepmd_data', set_size = dsys.get_nframes())
  File "/home/wqt/anaconda2/envs/deepmd/lib/python3.9/site-packages/dpdata/system.py", line 136, in to
    return self.to_fmt_obj(load_format(fmt), *args, **kwargs)
  File "/home/wqt/anaconda2/envs/deepmd/lib/python3.9/site-packages/dpdata/system.py", line 903, in to_fmt_obj
    return fmtobj.to_labeled_system(self.data, *args, **kwargs)
  File "/home/wqt/anaconda2/envs/deepmd/lib/python3.9/site-packages/dpdata/format.py", line 77, in to_labeled_system
    return self.to_system(data, *args, **kwargs)
  File "/home/wqt/anaconda2/envs/deepmd/lib/python3.9/site-packages/dpdata/plugins/deepmd.py", line 52, in to_system
    dpdata.deepmd.comp.dump(
  File "/home/wqt/anaconda2/envs/deepmd/lib/python3.9/site-packages/dpdata/deepmd/comp.py", line 85, in dump
    coords = np.reshape(data['coords'],   [nframes, -1]).astype(comp_prec)
  File "<__array_function__ internals>", line 5, in reshape
  File "/home/wqt/anaconda2/envs/deepmd/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/wqt/anaconda2/envs/deepmd/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 0 into shape (0,newaxis)
[dp.zip](https://github.com/deepmodeling/dpdata/files/9421079/dp.zip)

**Comment by HuangJiameng** [comment]
Your OUTCAR is not converged. Please check it.

**Comment by BraunSakai** [comment]
Thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月25日(星期四) 下午2:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [deepmodeling/dpdata] [BUG]When I use a script to convert OUTCAR to npy format, I encounter the following error： (Issue #348)





 
Your OUTCAR is not converged. Please check it.
