### ISSUE TITLE
[BUG]RuntimeError: system has virials, but this does not

### ISSUE THREAD

**Issue by JiangXiaoMingSan** [deepmodeling/dpdata#682]
### Bug summary

When I use dpdata to convert a file in xyz format to npy format, I get an error saying that the xyz file contains virials. But I checked the entire xyz file and it doesn't contain virials. The previous issue also reported this issue, stating that it was a bug and had been fixed. Later, I upgraded dpdata, and the current version is v0.2.19. I think I need your help.

### dpdata Version

dpdata v0.2.19

### Input Files, Running Commands, Error Log, etc.

import dpdata
xyz_multi_systems = dpdata.MultiSystems.from_file("db_HEA_v2.xyz", fmt="quip/gap/xyz"
                    ).to('deepmd/npy', '5alloy_train_data', set_size=3000)

### Steps to Reproduce

Traceback (most recent call last):
  File "/work/home/jiangmingxuan/alloy_test/TaNiWMoV/xyz2npy.py", line 3, in <module>
    xyz_multi_systems = dpdata.MultiSystems.from_file("db_HEA_v2.xyz", fmt="quip/gap/xyz"
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/home/jiangmingxuan/software/miniconda3/envs/dpgen/lib/python3.12/site-packages/dpdata/system.py", line 1445, in from_file
    multi_systems.load_systems_from_file(file_name=file_name, fmt=fmt, **kwargs)
  File "/work/home/jiangmingxuan/software/miniconda3/envs/dpgen/lib/python3.12/site-packages/dpdata/system.py", line 1469, in load_systems_from_file
    return self.from_fmt_obj(load_format(fmt), file_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/home/jiangmingxuan/software/miniconda3/envs/dpgen/lib/python3.12/site-packages/dpdata/system.py", line 1364, in from_fmt_obj
    self.append(system)
  File "/work/home/jiangmingxuan/software/miniconda3/envs/dpgen/lib/python3.12/site-packages/dpdata/system.py", line 1485, in append
    self.__append(system)
  File "/work/home/jiangmingxuan/software/miniconda3/envs/dpgen/lib/python3.12/site-packages/dpdata/system.py", line 1500, in __append
    self.systems[formula].append(system)
  File "/work/home/jiangmingxuan/software/miniconda3/envs/dpgen/lib/python3.12/site-packages/dpdata/system.py", line 510, in append
    raise RuntimeError(f"system has {tt.name}, but this does not")
RuntimeError: system has virials, but this does not

**Comment by njzjz** [comment]
Could you provide a file to reproduce the error?

**Comment by JiangXiaoMingSan** [comment]
[Mo-W-Ta.zip](https://github.com/user-attachments/files/16279463/Mo-W-Ta.zip)
I have provided my input file and script for your reference. After trying, I found that 'dboW-Mo-Ta_test. xyz' can be successfully converted to an npy format file, but 'dboW-Mo-Ta_rain. xyz' still reports an error

**Comment by njzjz** [comment]
When executing `grep virial db_W-Mo-Ta_train.xyz`, I can see lots of output showing some frames contain virials.

**Comment by JiangXiaoMingSan** [comment]
Sorry, there was an error in my previous search command that prevented me from retrieving the virial in the file. After deleting them, dpdata successfully ran. Thank you for your answer
